# Generated by Django 3.0.6 on 2020-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_code',
            field=models.CharField(max_length=10),
        ),
    ]
